### ISSUE TITLE
Memory requirements for robust_self_training.py

### ISSUE THREAD

**Issue by gwding** [yaircarmon/semisup-adv#2]
Thanks for opensource the code!
Having a question on the memory requirement for running `robust_self_training.py` under default arguments. The readme says `We tested this code on GPUs with 12GB of memory. `, but I observed that it needs `16099MiB` on P100 GPUs (tested after out of memory on 1080 Ti which has 11GB).
Wondering if this is normal?

**Comment by gwding** [comment]
Also if we want to adapted it to run on 1080Ti, I guess batch_size should be changed, do you suggest other changes with it?

**Comment by yaircarmon** [comment]
Thank you for your interest and comment! The readme was not completely clear: we tested the code on *two* Titan Xp GPU's with 12GB of memory each. The total memory requirement for adversarial training was indeed around 16GB. If you need to train on a single GPU, the easiest modification would be to decrease batch_size and if necessary also test_batch_size. You might also want to consider training a smaller model (e.g., wrn-40-2) which would require substantially less memory and time.

**Comment by gwding** [comment]
Thanks for the quick reply! Just to confirm, this is basically saying to reproduce the results exactly, we should use a 2-GPU data parallelism, where the batch_normalization is done on each GPU separately?

**Comment by yaircarmon** [comment]
For the most exact reproduction of our paper you should use 4 GPU's for adversarial training and 2 GPU's for stability training (with batch normalization on each GPU separately as in our code). See Appendix B.2 of our paper for some running time documentation. However, I believe that using 2 GPU's instead of 4 should have a negligible impact on performance of the learned model.

**Comment by gwding** [comment]
Thanks for the detailed answer!
